[project]
name = "jhu"
version = "1.6.6"
description = "Join Happy Universe"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bcrypt>=4.2.1",
    "pycryptodomex>=3.21.0",
    "python-jose>=3.3.0",
    "pytz>=2024.2",
    "requests>=2.32.3",
    "sqlalchemy>=2.0.36",
]
